export const cartActionTypes = {
    TOGGLE_HIDE_CART: 'TOGGLE_HIDE_CART',
    ADD_CART_ITEM: 'ADD_CART_ITEM',
    REMOVE_CARD_ITEM: "REMOVE_CARD_ITEM",
    REMOVE_ONE_CARD_ITEM: "REMOVE_ONE_CARD_ITEM",
};