name: Continuous Integration

on:
  push:
    branches-ignore: [master]
<<<<<<< HEAD
  pull_request:
=======
  pull request:
>>>>>>> b3e2356baef52e0022fa4b52fd99b68b2ee60c5c
    branches: [master]

jobs:
  first:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: yarn test
      - run: yarn build
        env:
          CI: ""
