name: Continuous Integration

on:
  push:
    branches-ignore: [master, dev]

jobs:
  CI_test_simple:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: cd client && npm ci
      - run: yarn test
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./client/coverage/clover.xml
          directory: ./client/coverage/
          fail_ci_if_error: true
      - run: yarn build
        env:
          CI: ""
