name: Continuous Deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: cd client && npm ci
      - run: yarn build
        env:
          CI: ""
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "project-live-react"
          heroku_email: "matija.prs@gmail.com"